### PR TITLE
Reference, UltimateDebtor/Creditor Name to max 143

### PR DESCRIPTION
**Pull request by KatKent**
@ClearlyEleanor can you please approve this?

### CODE REVIEW

**Review by ClearlyEleanor — APPROVED** [review]
Looks good to me. :-)

**Comment by simonness** [comment]
Looks great!

**Comment by KatKent** [comment]
Thank you both!

**Comment by KatKent** [comment]
Adding a note here to make it more obvious that this commit also included correcting the type shown for each webhook. (The one previously documented was incorrect.)

**Pull request merged**
